server:
  port: 8083

twilio:
  phoneNumber: "twilio_number"
  accountId: "twilio_accountId"
  authToken: "twilio_authToken"

spring:
  application:
    name: "microservice-sms"

appDescription: "Pragma Powerup"
appVersion: "1.0.0"
